# Generated by Django 6.0.6 on 2026-07-12 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kitap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200)),
                ('yazar', models.CharField(max_length=100)),
                ('fav', models.BooleanField(default=False)),
                ('sku', models.CharField(blank=True, max_length=50, null=True)),
                ('fiyat', models.FloatField()),
                ('adet', models.IntegerField()),
                ('tedarikci', models.CharField(max_length=100)),
            ],
        ),
    ]
